// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/queryusers.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ScholarPortal.Protos.Users {

  /// <summary>Holder for reflection information generated from Protos/queryusers.proto</summary>
  public static partial class QueryusersReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/queryusers.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QueryusersReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdQcm90b3MvcXVlcnl1c2Vycy5wcm90bxIKUXVlcnlVc2VycxofZ29vZ2xl",
            "L3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byIhCgtVc2VyUmVxdWVzdBISCgpp",
            "ZGVudGl0eUlkGAEgASgJIjQKDFVzZXJzUmVxdWVzdBIkCgNpZHMYASADKAsy",
            "Fy5RdWVyeVVzZXJzLlVzZXJSZXF1ZXN0IiEKDlVzZXJWYWxpZE1vZGVsEg8K",
            "B2lzVmFsaWQYASABKAgi7gQKCVVzZXJNb2RlbBISCgppZGVudGl0eUlkGAEg",
            "ASgJEhEKCWZpcnN0TmFtZRgCIAEoCRIQCghsYXN0TmFtZRgDIAEoCRIcChRz",
            "b2NpYWxTZWN1cml0eU51bWJlchgEIAEoCRItCgliaXJ0aGRhdGUYBSABKAsy",
            "Gi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg0KBWVtYWlsGAYgASgJEisK",
            "B2NyZWF0ZWQYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjkK",
            "BnN0YXR1cxgIIAEoDjIpLlF1ZXJ5VXNlcnMuVXNlck1vZGVsLlVzZXJTdGF0",
            "dXNFbnVtTW9kZWwSEgoKZW1wbG95ZWVJZBgJIAEoCRIzCgVyb2xlcxgKIAMo",
            "CzIkLlF1ZXJ5VXNlcnMuVXNlck1vZGVsLlVzZXJSb2xlc01vZGVsGr0BCg5V",
            "c2VyUm9sZXNNb2RlbBJFCgRyb2xlGAEgASgOMjcuUXVlcnlVc2Vycy5Vc2Vy",
            "TW9kZWwuVXNlclJvbGVzTW9kZWwuVXNlclJvbGVzRW51bU1vZGVsImQKElVz",
            "ZXJSb2xlc0VudW1Nb2RlbBILCgdTVFVERU5UEAASCQoFU1RBRkYQARILCgdG",
            "QUNVTFRZEAISEQoNQURNSU5JU1RSQVRPUhADEhYKElNVUEVSQURNSU5JU1RS",
            "QVRPUhAEIlsKE1VzZXJTdGF0dXNFbnVtTW9kZWwSCwoHVU5LTk9XThAAEgsK",
            "B0NSRUFURUQQARIOCgpSRUdJU1RFUkVEEAISCwoHSU5WQUxJRBADEg0KCVNV",
            "U1BFTkRFRBAEIjIKClVzZXJzTW9kZWwSJAoFdXNlcnMYASADKAsyFS5RdWVy",
            "eVVzZXJzLlVzZXJNb2RlbDLQAQoRUXVlcnlVc2Vyc1NlcnZpY2USQgoLSXNW",
            "YWxpZFVzZXISFy5RdWVyeVVzZXJzLlVzZXJSZXF1ZXN0GhouUXVlcnlVc2Vy",
            "cy5Vc2VyVmFsaWRNb2RlbBI5CgdHZXRVc2VyEhcuUXVlcnlVc2Vycy5Vc2Vy",
            "UmVxdWVzdBoVLlF1ZXJ5VXNlcnMuVXNlck1vZGVsEjwKCEdldFVzZXJzEhgu",
            "UXVlcnlVc2Vycy5Vc2Vyc1JlcXVlc3QaFi5RdWVyeVVzZXJzLlVzZXJzTW9k",
            "ZWxCHaoCGlNjaG9sYXJQb3J0YWwuUHJvdG9zLlVzZXJzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Users.UserRequest), global::ScholarPortal.Protos.Users.UserRequest.Parser, new[]{ "IdentityId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Users.UsersRequest), global::ScholarPortal.Protos.Users.UsersRequest.Parser, new[]{ "Ids" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Users.UserValidModel), global::ScholarPortal.Protos.Users.UserValidModel.Parser, new[]{ "IsValid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Users.UserModel), global::ScholarPortal.Protos.Users.UserModel.Parser, new[]{ "IdentityId", "FirstName", "LastName", "SocialSecurityNumber", "Birthdate", "Email", "Created", "Status", "EmployeeId", "Roles" }, null, new[]{ typeof(global::ScholarPortal.Protos.Users.UserModel.Types.UserStatusEnumModel) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel), global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Parser, new[]{ "Role" }, null, new[]{ typeof(global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Types.UserRolesEnumModel) }, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Users.UsersModel), global::ScholarPortal.Protos.Users.UsersModel.Parser, new[]{ "Users" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UserRequest : pb::IMessage<UserRequest> {
    private static readonly pb::MessageParser<UserRequest> _parser = new pb::MessageParser<UserRequest>(() => new UserRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScholarPortal.Protos.Users.QueryusersReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserRequest(UserRequest other) : this() {
      identityId_ = other.identityId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserRequest Clone() {
      return new UserRequest(this);
    }

    /// <summary>Field number for the "identityId" field.</summary>
    public const int IdentityIdFieldNumber = 1;
    private string identityId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdentityId {
      get { return identityId_; }
      set {
        identityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdentityId != other.IdentityId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdentityId.Length != 0) hash ^= IdentityId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IdentityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdentityId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdentityId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdentityId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserRequest other) {
      if (other == null) {
        return;
      }
      if (other.IdentityId.Length != 0) {
        IdentityId = other.IdentityId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdentityId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UsersRequest : pb::IMessage<UsersRequest> {
    private static readonly pb::MessageParser<UsersRequest> _parser = new pb::MessageParser<UsersRequest>(() => new UsersRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UsersRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScholarPortal.Protos.Users.QueryusersReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsersRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsersRequest(UsersRequest other) : this() {
      ids_ = other.ids_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsersRequest Clone() {
      return new UsersRequest(this);
    }

    /// <summary>Field number for the "ids" field.</summary>
    public const int IdsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ScholarPortal.Protos.Users.UserRequest> _repeated_ids_codec
        = pb::FieldCodec.ForMessage(10, global::ScholarPortal.Protos.Users.UserRequest.Parser);
    private readonly pbc::RepeatedField<global::ScholarPortal.Protos.Users.UserRequest> ids_ = new pbc::RepeatedField<global::ScholarPortal.Protos.Users.UserRequest>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ScholarPortal.Protos.Users.UserRequest> Ids {
      get { return ids_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UsersRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UsersRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!ids_.Equals(other.ids_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= ids_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      ids_.WriteTo(output, _repeated_ids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += ids_.CalculateSize(_repeated_ids_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UsersRequest other) {
      if (other == null) {
        return;
      }
      ids_.Add(other.ids_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ids_.AddEntriesFrom(input, _repeated_ids_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class UserValidModel : pb::IMessage<UserValidModel> {
    private static readonly pb::MessageParser<UserValidModel> _parser = new pb::MessageParser<UserValidModel>(() => new UserValidModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserValidModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScholarPortal.Protos.Users.QueryusersReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserValidModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserValidModel(UserValidModel other) : this() {
      isValid_ = other.isValid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserValidModel Clone() {
      return new UserValidModel(this);
    }

    /// <summary>Field number for the "isValid" field.</summary>
    public const int IsValidFieldNumber = 1;
    private bool isValid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsValid {
      get { return isValid_; }
      set {
        isValid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserValidModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserValidModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsValid != other.IsValid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IsValid != false) hash ^= IsValid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IsValid != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsValid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IsValid != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserValidModel other) {
      if (other == null) {
        return;
      }
      if (other.IsValid != false) {
        IsValid = other.IsValid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsValid = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UserModel : pb::IMessage<UserModel> {
    private static readonly pb::MessageParser<UserModel> _parser = new pb::MessageParser<UserModel>(() => new UserModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScholarPortal.Protos.Users.QueryusersReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserModel(UserModel other) : this() {
      identityId_ = other.identityId_;
      firstName_ = other.firstName_;
      lastName_ = other.lastName_;
      socialSecurityNumber_ = other.socialSecurityNumber_;
      birthdate_ = other.birthdate_ != null ? other.birthdate_.Clone() : null;
      email_ = other.email_;
      created_ = other.created_ != null ? other.created_.Clone() : null;
      status_ = other.status_;
      employeeId_ = other.employeeId_;
      roles_ = other.roles_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserModel Clone() {
      return new UserModel(this);
    }

    /// <summary>Field number for the "identityId" field.</summary>
    public const int IdentityIdFieldNumber = 1;
    private string identityId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdentityId {
      get { return identityId_; }
      set {
        identityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "firstName" field.</summary>
    public const int FirstNameFieldNumber = 2;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastName" field.</summary>
    public const int LastNameFieldNumber = 3;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "socialSecurityNumber" field.</summary>
    public const int SocialSecurityNumberFieldNumber = 4;
    private string socialSecurityNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SocialSecurityNumber {
      get { return socialSecurityNumber_; }
      set {
        socialSecurityNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "birthdate" field.</summary>
    public const int BirthdateFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp birthdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Birthdate {
      get { return birthdate_; }
      set {
        birthdate_ = value;
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 6;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "created" field.</summary>
    public const int CreatedFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp created_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Created {
      get { return created_; }
      set {
        created_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 8;
    private global::ScholarPortal.Protos.Users.UserModel.Types.UserStatusEnumModel status_ = global::ScholarPortal.Protos.Users.UserModel.Types.UserStatusEnumModel.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ScholarPortal.Protos.Users.UserModel.Types.UserStatusEnumModel Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "employeeId" field.</summary>
    public const int EmployeeIdFieldNumber = 9;
    private string employeeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EmployeeId {
      get { return employeeId_; }
      set {
        employeeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "roles" field.</summary>
    public const int RolesFieldNumber = 10;
    private static readonly pb::FieldCodec<global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel> _repeated_roles_codec
        = pb::FieldCodec.ForMessage(82, global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Parser);
    private readonly pbc::RepeatedField<global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel> roles_ = new pbc::RepeatedField<global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel> Roles {
      get { return roles_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdentityId != other.IdentityId) return false;
      if (FirstName != other.FirstName) return false;
      if (LastName != other.LastName) return false;
      if (SocialSecurityNumber != other.SocialSecurityNumber) return false;
      if (!object.Equals(Birthdate, other.Birthdate)) return false;
      if (Email != other.Email) return false;
      if (!object.Equals(Created, other.Created)) return false;
      if (Status != other.Status) return false;
      if (EmployeeId != other.EmployeeId) return false;
      if(!roles_.Equals(other.roles_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdentityId.Length != 0) hash ^= IdentityId.GetHashCode();
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (SocialSecurityNumber.Length != 0) hash ^= SocialSecurityNumber.GetHashCode();
      if (birthdate_ != null) hash ^= Birthdate.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (created_ != null) hash ^= Created.GetHashCode();
      if (Status != global::ScholarPortal.Protos.Users.UserModel.Types.UserStatusEnumModel.Unknown) hash ^= Status.GetHashCode();
      if (EmployeeId.Length != 0) hash ^= EmployeeId.GetHashCode();
      hash ^= roles_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IdentityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdentityId);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LastName);
      }
      if (SocialSecurityNumber.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SocialSecurityNumber);
      }
      if (birthdate_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Birthdate);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Email);
      }
      if (created_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Created);
      }
      if (Status != global::ScholarPortal.Protos.Users.UserModel.Types.UserStatusEnumModel.Unknown) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Status);
      }
      if (EmployeeId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(EmployeeId);
      }
      roles_.WriteTo(output, _repeated_roles_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdentityId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdentityId);
      }
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (SocialSecurityNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SocialSecurityNumber);
      }
      if (birthdate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Birthdate);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (created_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Created);
      }
      if (Status != global::ScholarPortal.Protos.Users.UserModel.Types.UserStatusEnumModel.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (EmployeeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EmployeeId);
      }
      size += roles_.CalculateSize(_repeated_roles_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserModel other) {
      if (other == null) {
        return;
      }
      if (other.IdentityId.Length != 0) {
        IdentityId = other.IdentityId;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      if (other.SocialSecurityNumber.Length != 0) {
        SocialSecurityNumber = other.SocialSecurityNumber;
      }
      if (other.birthdate_ != null) {
        if (birthdate_ == null) {
          Birthdate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Birthdate.MergeFrom(other.Birthdate);
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.created_ != null) {
        if (created_ == null) {
          Created = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Created.MergeFrom(other.Created);
      }
      if (other.Status != global::ScholarPortal.Protos.Users.UserModel.Types.UserStatusEnumModel.Unknown) {
        Status = other.Status;
      }
      if (other.EmployeeId.Length != 0) {
        EmployeeId = other.EmployeeId;
      }
      roles_.Add(other.roles_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdentityId = input.ReadString();
            break;
          }
          case 18: {
            FirstName = input.ReadString();
            break;
          }
          case 26: {
            LastName = input.ReadString();
            break;
          }
          case 34: {
            SocialSecurityNumber = input.ReadString();
            break;
          }
          case 42: {
            if (birthdate_ == null) {
              Birthdate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Birthdate);
            break;
          }
          case 50: {
            Email = input.ReadString();
            break;
          }
          case 58: {
            if (created_ == null) {
              Created = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Created);
            break;
          }
          case 64: {
            Status = (global::ScholarPortal.Protos.Users.UserModel.Types.UserStatusEnumModel) input.ReadEnum();
            break;
          }
          case 74: {
            EmployeeId = input.ReadString();
            break;
          }
          case 82: {
            roles_.AddEntriesFrom(input, _repeated_roles_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the UserModel message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum UserStatusEnumModel {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("CREATED")] Created = 1,
        [pbr::OriginalName("REGISTERED")] Registered = 2,
        [pbr::OriginalName("INVALID")] Invalid = 3,
        [pbr::OriginalName("SUSPENDED")] Suspended = 4,
      }

      public sealed partial class UserRolesModel : pb::IMessage<UserRolesModel> {
        private static readonly pb::MessageParser<UserRolesModel> _parser = new pb::MessageParser<UserRolesModel>(() => new UserRolesModel());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<UserRolesModel> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ScholarPortal.Protos.Users.UserModel.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserRolesModel() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserRolesModel(UserRolesModel other) : this() {
          role_ = other.role_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserRolesModel Clone() {
          return new UserRolesModel(this);
        }

        /// <summary>Field number for the "role" field.</summary>
        public const int RoleFieldNumber = 1;
        private global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Types.UserRolesEnumModel role_ = global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Types.UserRolesEnumModel.Student;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Types.UserRolesEnumModel Role {
          get { return role_; }
          set {
            role_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as UserRolesModel);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(UserRolesModel other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Role != other.Role) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Role != global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Types.UserRolesEnumModel.Student) hash ^= Role.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Role != global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Types.UserRolesEnumModel.Student) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Role);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Role != global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Types.UserRolesEnumModel.Student) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Role);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(UserRolesModel other) {
          if (other == null) {
            return;
          }
          if (other.Role != global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Types.UserRolesEnumModel.Student) {
            Role = other.Role;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Role = (global::ScholarPortal.Protos.Users.UserModel.Types.UserRolesModel.Types.UserRolesEnumModel) input.ReadEnum();
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the UserRolesModel message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types {
          public enum UserRolesEnumModel {
            [pbr::OriginalName("STUDENT")] Student = 0,
            [pbr::OriginalName("STAFF")] Staff = 1,
            [pbr::OriginalName("FACULTY")] Faculty = 2,
            [pbr::OriginalName("ADMINISTRATOR")] Administrator = 3,
            [pbr::OriginalName("SUPERADMINISTRATOR")] Superadministrator = 4,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  public sealed partial class UsersModel : pb::IMessage<UsersModel> {
    private static readonly pb::MessageParser<UsersModel> _parser = new pb::MessageParser<UsersModel>(() => new UsersModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UsersModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScholarPortal.Protos.Users.QueryusersReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsersModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsersModel(UsersModel other) : this() {
      users_ = other.users_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsersModel Clone() {
      return new UsersModel(this);
    }

    /// <summary>Field number for the "users" field.</summary>
    public const int UsersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ScholarPortal.Protos.Users.UserModel> _repeated_users_codec
        = pb::FieldCodec.ForMessage(10, global::ScholarPortal.Protos.Users.UserModel.Parser);
    private readonly pbc::RepeatedField<global::ScholarPortal.Protos.Users.UserModel> users_ = new pbc::RepeatedField<global::ScholarPortal.Protos.Users.UserModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ScholarPortal.Protos.Users.UserModel> Users {
      get { return users_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UsersModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UsersModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!users_.Equals(other.users_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= users_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      users_.WriteTo(output, _repeated_users_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += users_.CalculateSize(_repeated_users_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UsersModel other) {
      if (other == null) {
        return;
      }
      users_.Add(other.users_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            users_.AddEntriesFrom(input, _repeated_users_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
