// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/queryemployees.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ScholarPortal.Protos.Employees {

  /// <summary>Holder for reflection information generated from Protos/queryemployees.proto</summary>
  public static partial class QueryemployeesReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/queryemployees.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QueryemployeesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtQcm90b3MvcXVlcnllbXBsb3llZXMucHJvdG8SDlF1ZXJ5RW1wbG95ZWVz",
            "Gh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGhdQcm90b3MvcXVl",
            "cnl1c2Vycy5wcm90byIlCg9FbXBsb3llZVJlcXVlc3QSEgoKZW1wbG95ZWVJ",
            "ZBgBIAEoCSJIChBFbXBsb3llZXNSZXF1ZXN0EjQKC2VtcGxveWVlSWRzGAEg",
            "AygLMh8uUXVlcnlFbXBsb3llZXMuRW1wbG95ZWVSZXF1ZXN0Ih0KD0VtcGxv",
            "eWVlSWRNb2RlbBIKCgJpZBgBIAEoCSKbAgoNRW1wbG95ZWVNb2RlbBIKCgJp",
            "ZBgBIAEoCRINCgV0aXRsZRgCIAEoCRI6CgVzdGF0ZRgDIAEoDjIrLlF1ZXJ5",
            "RW1wbG95ZWVzLkVtcGxveWVlTW9kZWwuRW1wbG95ZWVTdGF0ZRIrCgdjcmVh",
            "dGVkGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIjCgR1c2Vy",
            "GAUgASgLMhUuUXVlcnlVc2Vycy5Vc2VyTW9kZWwiYQoNRW1wbG95ZWVTdGF0",
            "ZRILCgdVTktOT1dOEAASCQoFVkFMSUQQARIOCgpJTkNPTVBMRVRFEAISDgoK",
            "U1VTUElDSU9VUxADEgoKBkxPQ0tFRBAEEgwKCElOQUNUSVZFEAUiRQoRRW1w",
            "bG95ZWVMaXN0TW9kZWwSMAoJZW1wbG95ZWVzGAEgAygLMh0uUXVlcnlFbXBs",
            "b3llZXMuRW1wbG95ZWVNb2RlbDKQAgoVUXVlcnlFbXBsb3llZXNTZXJ2aWNl",
            "ElMKD0lzVmFsaWRFbXBsb3llZRIfLlF1ZXJ5RW1wbG95ZWVzLkVtcGxveWVl",
            "UmVxdWVzdBofLlF1ZXJ5RW1wbG95ZWVzLkVtcGxveWVlSWRNb2RlbBJNCgtH",
            "ZXRFbXBsb3llZRIfLlF1ZXJ5RW1wbG95ZWVzLkVtcGxveWVlUmVxdWVzdBod",
            "LlF1ZXJ5RW1wbG95ZWVzLkVtcGxveWVlTW9kZWwSUwoMR2V0RW1wbG95ZWVz",
            "EiAuUXVlcnlFbXBsb3llZXMuRW1wbG95ZWVzUmVxdWVzdBohLlF1ZXJ5RW1w",
            "bG95ZWVzLkVtcGxveWVlTGlzdE1vZGVsQiGqAh5TY2hvbGFyUG9ydGFsLlBy",
            "b3Rvcy5FbXBsb3llZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::ScholarPortal.Protos.Users.QueryusersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Employees.EmployeeRequest), global::ScholarPortal.Protos.Employees.EmployeeRequest.Parser, new[]{ "EmployeeId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Employees.EmployeesRequest), global::ScholarPortal.Protos.Employees.EmployeesRequest.Parser, new[]{ "EmployeeIds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Employees.EmployeeIdModel), global::ScholarPortal.Protos.Employees.EmployeeIdModel.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Employees.EmployeeModel), global::ScholarPortal.Protos.Employees.EmployeeModel.Parser, new[]{ "Id", "Title", "State", "Created", "User" }, null, new[]{ typeof(global::ScholarPortal.Protos.Employees.EmployeeModel.Types.EmployeeState) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ScholarPortal.Protos.Employees.EmployeeListModel), global::ScholarPortal.Protos.Employees.EmployeeListModel.Parser, new[]{ "Employees" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EmployeeRequest : pb::IMessage<EmployeeRequest> {
    private static readonly pb::MessageParser<EmployeeRequest> _parser = new pb::MessageParser<EmployeeRequest>(() => new EmployeeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EmployeeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScholarPortal.Protos.Employees.QueryemployeesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeRequest(EmployeeRequest other) : this() {
      employeeId_ = other.employeeId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeRequest Clone() {
      return new EmployeeRequest(this);
    }

    /// <summary>Field number for the "employeeId" field.</summary>
    public const int EmployeeIdFieldNumber = 1;
    private string employeeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EmployeeId {
      get { return employeeId_; }
      set {
        employeeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EmployeeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EmployeeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EmployeeId != other.EmployeeId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EmployeeId.Length != 0) hash ^= EmployeeId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EmployeeId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EmployeeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EmployeeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EmployeeId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EmployeeRequest other) {
      if (other == null) {
        return;
      }
      if (other.EmployeeId.Length != 0) {
        EmployeeId = other.EmployeeId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EmployeeId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EmployeesRequest : pb::IMessage<EmployeesRequest> {
    private static readonly pb::MessageParser<EmployeesRequest> _parser = new pb::MessageParser<EmployeesRequest>(() => new EmployeesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EmployeesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScholarPortal.Protos.Employees.QueryemployeesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeesRequest(EmployeesRequest other) : this() {
      employeeIds_ = other.employeeIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeesRequest Clone() {
      return new EmployeesRequest(this);
    }

    /// <summary>Field number for the "employeeIds" field.</summary>
    public const int EmployeeIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ScholarPortal.Protos.Employees.EmployeeRequest> _repeated_employeeIds_codec
        = pb::FieldCodec.ForMessage(10, global::ScholarPortal.Protos.Employees.EmployeeRequest.Parser);
    private readonly pbc::RepeatedField<global::ScholarPortal.Protos.Employees.EmployeeRequest> employeeIds_ = new pbc::RepeatedField<global::ScholarPortal.Protos.Employees.EmployeeRequest>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ScholarPortal.Protos.Employees.EmployeeRequest> EmployeeIds {
      get { return employeeIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EmployeesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EmployeesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!employeeIds_.Equals(other.employeeIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= employeeIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      employeeIds_.WriteTo(output, _repeated_employeeIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += employeeIds_.CalculateSize(_repeated_employeeIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EmployeesRequest other) {
      if (other == null) {
        return;
      }
      employeeIds_.Add(other.employeeIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            employeeIds_.AddEntriesFrom(input, _repeated_employeeIds_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class EmployeeIdModel : pb::IMessage<EmployeeIdModel> {
    private static readonly pb::MessageParser<EmployeeIdModel> _parser = new pb::MessageParser<EmployeeIdModel>(() => new EmployeeIdModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EmployeeIdModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScholarPortal.Protos.Employees.QueryemployeesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeIdModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeIdModel(EmployeeIdModel other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeIdModel Clone() {
      return new EmployeeIdModel(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EmployeeIdModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EmployeeIdModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EmployeeIdModel other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EmployeeModel : pb::IMessage<EmployeeModel> {
    private static readonly pb::MessageParser<EmployeeModel> _parser = new pb::MessageParser<EmployeeModel>(() => new EmployeeModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EmployeeModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScholarPortal.Protos.Employees.QueryemployeesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeModel(EmployeeModel other) : this() {
      id_ = other.id_;
      title_ = other.title_;
      state_ = other.state_;
      created_ = other.created_ != null ? other.created_.Clone() : null;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeModel Clone() {
      return new EmployeeModel(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 2;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 3;
    private global::ScholarPortal.Protos.Employees.EmployeeModel.Types.EmployeeState state_ = global::ScholarPortal.Protos.Employees.EmployeeModel.Types.EmployeeState.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ScholarPortal.Protos.Employees.EmployeeModel.Types.EmployeeState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "created" field.</summary>
    public const int CreatedFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp created_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Created {
      get { return created_; }
      set {
        created_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 5;
    private global::ScholarPortal.Protos.Users.UserModel user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ScholarPortal.Protos.Users.UserModel User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EmployeeModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EmployeeModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Title != other.Title) return false;
      if (State != other.State) return false;
      if (!object.Equals(Created, other.Created)) return false;
      if (!object.Equals(User, other.User)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (State != global::ScholarPortal.Protos.Employees.EmployeeModel.Types.EmployeeState.Unknown) hash ^= State.GetHashCode();
      if (created_ != null) hash ^= Created.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (State != global::ScholarPortal.Protos.Employees.EmployeeModel.Types.EmployeeState.Unknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) State);
      }
      if (created_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Created);
      }
      if (user_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(User);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (State != global::ScholarPortal.Protos.Employees.EmployeeModel.Types.EmployeeState.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (created_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Created);
      }
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EmployeeModel other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.State != global::ScholarPortal.Protos.Employees.EmployeeModel.Types.EmployeeState.Unknown) {
        State = other.State;
      }
      if (other.created_ != null) {
        if (created_ == null) {
          Created = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Created.MergeFrom(other.Created);
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::ScholarPortal.Protos.Users.UserModel();
        }
        User.MergeFrom(other.User);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 24: {
            State = (global::ScholarPortal.Protos.Employees.EmployeeModel.Types.EmployeeState) input.ReadEnum();
            break;
          }
          case 34: {
            if (created_ == null) {
              Created = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Created);
            break;
          }
          case 42: {
            if (user_ == null) {
              User = new global::ScholarPortal.Protos.Users.UserModel();
            }
            input.ReadMessage(User);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the EmployeeModel message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum EmployeeState {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("VALID")] Valid = 1,
        [pbr::OriginalName("INCOMPLETE")] Incomplete = 2,
        [pbr::OriginalName("SUSPICIOUS")] Suspicious = 3,
        [pbr::OriginalName("LOCKED")] Locked = 4,
        [pbr::OriginalName("INACTIVE")] Inactive = 5,
      }

    }
    #endregion

  }

  public sealed partial class EmployeeListModel : pb::IMessage<EmployeeListModel> {
    private static readonly pb::MessageParser<EmployeeListModel> _parser = new pb::MessageParser<EmployeeListModel>(() => new EmployeeListModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EmployeeListModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ScholarPortal.Protos.Employees.QueryemployeesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeListModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeListModel(EmployeeListModel other) : this() {
      employees_ = other.employees_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmployeeListModel Clone() {
      return new EmployeeListModel(this);
    }

    /// <summary>Field number for the "employees" field.</summary>
    public const int EmployeesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ScholarPortal.Protos.Employees.EmployeeModel> _repeated_employees_codec
        = pb::FieldCodec.ForMessage(10, global::ScholarPortal.Protos.Employees.EmployeeModel.Parser);
    private readonly pbc::RepeatedField<global::ScholarPortal.Protos.Employees.EmployeeModel> employees_ = new pbc::RepeatedField<global::ScholarPortal.Protos.Employees.EmployeeModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ScholarPortal.Protos.Employees.EmployeeModel> Employees {
      get { return employees_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EmployeeListModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EmployeeListModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!employees_.Equals(other.employees_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= employees_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      employees_.WriteTo(output, _repeated_employees_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += employees_.CalculateSize(_repeated_employees_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EmployeeListModel other) {
      if (other == null) {
        return;
      }
      employees_.Add(other.employees_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            employees_.AddEntriesFrom(input, _repeated_employees_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
